/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'warm-off-white': '#FAFAF8',
        // InciFind palette
        'mist': '#f7f8f3',
        'pine-900': '#163c2a',
        'pine-800': '#1e563b',
        'pine-700': '#28724c',
        'pine-600': '#3d8a61',
        'pine-200': '#d8eadb',
        'pine-100': '#edf6ee',
        'ink': '#17221c',
        'ink-soft': '#647068',
        'ink-muted': '#8a948d',
        'sun': '#f4c95d',
        'sun-bg': '#fff7dc',
        'clay': '#d9584f',
        'clay-bg': '#fff0ee',
        'line': '#e5e9e3',
        'text-primary': '#1A1A18',
        'text-secondary': '#6B6B66',
        'warm-stone': '#D4C5B9',
        'soft-sage': '#A8B8A8',
        'muted-terra': '#C9956B',
        'soft-cream': '#F5F1ED',
        'badge-fragrance-bg': '#E8D4C4',
        'badge-fragrance-text': '#8B6F5F',
        'badge-photo-bg': '#D9E8D4',
        'badge-photo-text': '#6B8B6F',
        'badge-regulated-bg': '#E8D9D4',
        'badge-regulated-text': '#8B6B6F',
        'badge-alcohol-bg': '#F0E8D4',
        'badge-alcohol-text': '#7B7B6F',
        'disclosure-bg': '#F5F1ED',
        'disclosure-text': '#6B6B66',
      },
      fontFamily: {
        'serif': ['Georgia', 'Garamond', 'serif'],
        'sans': ['Inter', 'system-ui', 'sans-serif'],
        'mono': ['SF Mono', 'Menlo', 'monospace'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.2', fontWeight: '600' }],
        'display-md': ['32px', { lineHeight: '1.3', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '1.8' }],
        'body-md': ['15px', { lineHeight: '1.6' }],
        'body-sm': ['14px', { lineHeight: '1.6' }],
        'mono-sm': ['14px', { lineHeight: '1.5', fontFamily: 'monospace' }],
      },
      spacing: {
        'xs': '4px',
        'sm': '8px',
        'md': '12px',
        'lg': '16px',
        'xl': '24px',
        '2xl': '32px',
        '3xl': '48px',
        '4xl': '64px',
      },
      borderRadius: {
        'subtle': '4px',
        'sm': '6px',
        'md': '8px',
      },
      boxShadow: {
        'subtle': '0 1px 3px rgba(0, 0, 0, 0.08)',
        'sm': '0 2px 6px rgba(0, 0, 0, 0.1)',
      },
      transitionDuration: {
        '300': '300ms',
        '400': '400ms',
      },
    },
  },
  plugins: [],
};
